import { StyleSheet } from 'react-native'

const CarFilCss = StyleSheet.create({
    CarFil:{
        height:600, 
    },
    CarType:{
        height:150,
        justifyContent:'center'
    },
    CarTypeChoose:{
        height:90,
        alignItems:'center',
        marginBottom:20,
        flexDirection:'row'
    },
    TypeCar:{
        height:80,
        width:80,
        backgroundColor:'#ECECEC',
        marginLeft:15,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:7
    },
    TypeMotor:{
        height:80,
        width:80,
        backgroundColor:'#ECECEC',
        marginLeft:20,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:7
    },
    CarStyle:{
        height:250,
    },
    CarStyleAll:{
        height:80,
        width:80,
        backgroundColor:'#ECECEC',
        marginLeft:15,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:7
    },
    CarStyleChoose:{
        height:90,
        alignItems:'center',
        marginBottom:20,
        flexDirection:'row',
        marginTop:20
    },
    SeatStyle1:{
        height:80,
        width:80,
        backgroundColor:'#ECECEC',
        marginLeft:15,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:7
    },
    SeatStyle2:{
        height:80,
        width:80,
        backgroundColor:'#ECECEC',
        marginLeft:20,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:7
    },
    SeatStyle3:{
        height:80,
        width:80,
        backgroundColor:'#ECECEC',
        marginLeft:20,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:7
    },
    CarBrand:{
        height:110,
    },
    ChooseBrand:{
        height:55,
        marginTop:15,
        width:'90%',
        alignSelf:'center',
        borderWidth:1,
        flexDirection:'row'
    },
    ChooseBrandButton1:{
        alignSelf:'baseline',
        width:'100%',
        backgroundColor: 'white',
    },
    ChooseBrandButton2:{
        width:'10%',
        position:'absolute',
        top:15,
        left: '90%',
        alignItems:'center',
        justifyContent:'center',
    },
    CarFilCloseButton:{
        width:'90%',
        backgroundColor:'#146C94',
        alignItems:'center',
        justifyContent:'center',
        height:50,
        alignSelf:'center',
        marginTop:15,
        borderRadius:3

    }
})
export default CarFilCss