import { StyleSheet } from 'react-native'
import React from 'react'

const LocateFilCss = StyleSheet.create({
    //LocationFilter
    LocationFil:{
        height:300,
        // backgroundColor:'red',
        width:'100%',
        alignSelf:'center'
    },
    Location1:{
        height:100,
        backgroundColor:'#ECECEC',
        alignSelf:'center',
        width:'95%',
        marginTop:30,
        flexDirection: 'row',
        borderRadius:10
    },
    Location2:{
        height:60,
        backgroundColor:'#ECECEC',
        marginTop:20,
        width:'95%',
        alignSelf:'center',
        borderRadius:10,
        flexDirection: 'row',
    },
    Location3:{
        height:60,
        marginTop:20,
        width:'95%',
        alignSelf:'center',
        borderRadius:10,
        flexDirection: 'row',
    },
    Locate1:{
        justifyContent:'center',
        alignItems:'center',
        width:'25%',
        height:100
    },
    Locate2:{
        justifyContent:'center',
        alignItems:'baseline',
        width:'45%',
        height:100
    },
    Locate3:{
        justifyContent:'center',
        alignItems:'center',
        width:'30%',
        height:100
    },
    Locate4:{
        justifyContent:'center',
        alignItems:'center',
        width:'20%',
        height:60
    },
    Locate5:{
        justifyContent:'center',
        alignItems:'baseline',
        width:'60%',
        height:60
    },
    Locate6:{
        justifyContent:'center',
        alignItems:'center',
        width:'20%',
        height:60
    },
    Locate7:{
        justifyContent:'center',
        alignItems:'center',
        width:'65%',
        height:60,
        backgroundColor:'#ECECEC',
        marginRight:20,
        flexDirection:'row',
        borderRadius:10
    },
    Locate8:{
        justifyContent:'center',
        alignItems:'center',
        width:'25%',
        height:60,
        backgroundColor:'#146C94',
        borderRadius:8,
    },
    Locate9:{
        justifyContent:'center',
        alignItems:'center',
        width:'20%',
        height:60,
    },
    Locate10:{
        justifyContent:'center',
        alignItems:'baseline',
        width:'60%',
        height:60
    },
    Locate11:{
        justifyContent:'center',
        alignItems:'center',
        width:'20%',
        height:60
    },
    Locate12:{
        justifyContent:'center',
        alignItems:'center',
        width:'100%',
        height:60,
        flexDirection:'row'
    },
    //LocationFilter
})
export default LocateFilCss